Bump nats client to v1.17.0
k3s-io/kine pull request #137
Opened 2022-09-21 19:14 UTC by caleblloyd

- Bumps the nats clinet to v1.17.0
- Fixes the `DbSize` function to call Stream Info in order to get the stream size

2022-09-21 19:27 UTC, brandond approved these changes

2022-09-21 22:13 UTC, brandond commented
Hmm, it looks like the tests for the new nats server versions failed due to the DB test never succeeding: https://drone-pr.k3s.io/k3s-io/kine/94/1/3

Does the `DB_CONNECTION_TEST` need to be updated for the new versions?

2022-09-21 22:14 UTC, brandond requested changes
Tests are failing

2022-09-22 02:31 UTC, brandond commented
No, it doesn't capture the actual output of the connection test. Best bet would probably be to start the database pod using the create command, and then test it with the test command.

We don't have an official support matrix; I kinda consider the minor versions that we have in the tests to be supported so if we're dropping v2.7 from the tests that says something.

2022-09-22 16:32 UTC, caleblloyd commented
I found the test issue, I had pasted an incorrect version into `DB_CONNECTION_TEST`; that is fixed

I am fine with keeping `2.7.4` in the tests...  I don't think we necessarily need to test every minor version of NATS, I don't want to bog down CI as NATS keeps publishing minor releases.  How does just testing `2.7.4` and the Current version of NATS sound?  Made that change too

2022-09-26 20:56 UTC, brandond approved these changes
https://drone-pr.k3s.io/k3s-io/kine/97/1/3

Ci failed but it looks like a flake; lgtm

2022-10-21 19:05 UTC, merged