Provide Dapper free build alternative
k3s-io/kine pull request #254
Opened 2023-12-08 18:26 UTC by dereknola

Signed-off-by: Derek Nola <derek.nola@suse.com>

## Changes
- 
- Consolidate the two validate scripts into one
- Bump dapper image in CI
- Nit: Spelling mistakes fixed

2023-12-08 22:41 UTC, brandond approved these changes

2023-12-08 22:42 UTC, brandond requested changes

2023-12-08 22:42 UTC, brandond commented on .drone.yml
> +  image: rancher/dapper:v0.6.0
I think I mentioned it on slack, but newer versions of dapper crash on arm, as seen in the CI logs. Don't bump this here.

2023-12-11 17:36 UTC, brandond approved these changes

2023-12-13 22:52 UTC, brandond commented
merge when ready!

2023-12-20 17:27 UTC, vitorsavian approved these changes

2023-12-20 17:42 UTC, merged