feat: support RISC-V 64
k3s-io/kine pull request #297
Opened 2024-05-07 14:26 UTC by shanduur

Treat it as POC, as I do not fully understand how the Dapper scripts work, but hey, it works for me!

How I tested it:

```sh
make ARCH=riscv64
docker run \
    --rm --interactive --tty \
    --volume=./bin/:/mnt/bin \
    --platform=linux/riscv64 \
    riscv64/busybox \
        /mnt/bin/kine
```

Closes #296

2024-05-30 17:44 UTC, dereknola requested changes

2024-05-30 17:44 UTC, dereknola commented on pkg/drivers/sqlite/sqlite_nocgo.go
> +	"github.com/glebarez/go-sqlite"
You seem to have duplicate imports of this and line 25

2024-05-30 17:44 UTC, dereknola commented on pkg/drivers/sqlite/sqlite_cgo.go
> +	"github.com/mattn/go-sqlite3"
Duplicate imports here and on line 24

2024-05-30 17:44 UTC, dereknola commented on go.mod
> +	modernc.org/sqlite v1.28.0
Is this related to `github.com/mattn/go-sqlite3`?

2024-05-30 18:53 UTC, brandond commented
Why are you changing the code at all? This should just build as-is on riscv64.

2024-10-31 22:42 UTC, shanduur commented
Anyone looking into this?

2025-01-13 20:01 UTC, shanduur commented
Hi @brandond ! Have you had time to look into this?

2025-01-15 17:42 UTC, vitorsavian approved these changes

2025-02-04 21:47 UTC, merged